#!/bin/bash
SOURCE_IMAGE=$BASE_OS:git

add_volume ~/.ssh:/comfreeze/.ssh

update_current_image $SOURCE_IMAGE

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

exec_command ${SOURCE_IMAGE} ${CONTAINER_ARGS}  "git $*"
