#!/bin/bash
SOURCE_IMAGE=$BASE_OS:yeoman

update_current_image $SOURCE_IMAGE

verbose "Running 'grunt $*' with args: $CONTAINER_ARGS"

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

$DOCKER_CMD run  \
$INTERACTIVE -t --rm=true \
 -v "$( pwd ):/overlay" \
 $CONTAINER_ARGS \
 $SOURCE_IMAGE "grunt $*"
