#!/bin/bash
SOURCE_IMAGE=${BASE_OS}:php5-cli

add_volume $( pwd ):/overlay

update_current_image ${SOURCE_IMAGE}

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

exec_command ${SOURCE_IMAGE} "~/.composer/vendor/bin/laravel $*"
