#!/bin/bash
SOURCE_IMAGE=$BASE_OS:mongo

update_current_image $SOURCE_IMAGE

verbose "Running 'mongo $*' with args: $CONTAINER_ARGS"

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

$DOCKER_CMD run  \
$INTERACTIVE -t --rm=true \
 $CONTAINER_ARGS \
 $SOURCE_IMAGE "/usr/bin/mongo $*"
