#!/bin/bash
SOURCE_IMAGE=${BASE_OS}:yeoman

add_volume $( pwd ):/overlay

update_current_image ${SOURCE_IMAGE}

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

exec_command ${SOURCE_IMAGE}  "sass $*"
