#!/bin/bash
VERSION=0.7.0
VERBOSE=false
RETURN_HOLDER=
FORCE=false
UPDATE=false
SELF_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P) && SELF_PATH=$SELF_PATH/$(basename -- "$0")

while [ -h "$SELF_PATH" ]; do
    DIR=$(dirname -- "$SELF_PATH")
    SYM=$(readlink "$SELF_PATH")
    SELF_PATH=$(cd $DIR && cd $(dirname -- "$SYM") && pwd)/$(basename -- "$SYM")
done

#
# Colorful ASCII sig - Just cause bubb
#
signature() {
	echo "$(tput bold)$(tput setaf 4)-[$(tput setaf 6)CFZ$(tput setaf 4)]- $(tput setaf 1)H$(tput sgr0)eadworks $(tput setaf 1)M$(tput sgr0)achination $(tput setaf 1)M$(tput sgr0)anagement$(tput sgr0) - v$VERSION"
}
#
# Help and usage (early to show for errors)
#
usage() {
    cat << EOF
hmm - helper with docker container tooling

hmm [feature] [params] action [options]

 FEATURES:
   -a, --actions       Show complete list of available actions
   -h, --help          Show brief help
   -i, --info          Show defined contants
   -F, --force         Manually force an operation, if allowed
   -V, --verbose       Enable debug messaging
   -U, --update        Update the base image powering the command
   --path              Display HMM home path

 PARAMS:
   -c (filename)       Direct configuration file specification (default: config.hmm)
   -e NAME=value       Define an internal environment variable
   -p (###:)###        Tunnel a port through the container [host:container]
   -v (/path:)/path    Mount a virtual volume into the container [host:container]
   -C (nsenter|ssh)    Select which access to use in helper calls

 OVERRIDES:
   NOTE: These options should come after a configuration specification to ensure
         that values are not overwritten by config load as params are processed FIFO
   -n (container_name) The raw container name (common handle)
   -R (registry)       A registry address to exchange image details, if not port 80
                       then must include port; e.g. localhost:5000 (no protocols).
   -B (base)           Base name of the image to the registry, a.k.a. repository.
   -T (tag_name)       The tag referenced on the image in the registry
   -P (parent)         The parent reference for spawning and serving
   -u (user)           The user for remote access features, if needed
EOF
}
#
# Verbosity helper
#
verbose() {
    if [[ $VERBOSE = true ]]; then
        echo $1
    fi
}
#
# Test configuration
#
check() {
    if [[ $CONTAINER_NAME = "-" ]]; then
        echo "ERROR: Invalid configuration!"
        usage
        exit 1
    fi
}
#
# Test empty parameters
#
not_empty() {
    if [[ $1 = "" ]]; then
        echo $2
        exit 1
    fi
}
#
# PID Lookup
#
container_pid() {
    RESULT=$( $DOCKER_CMD inspect --format {{.State.Pid}} $CONTAINER_NAME )
    RETURN_HOLDER=$RESULT
    return
}
#
# PORT Lookup
#
container_port() {
    RESULT=$( $DOCKER_CMD port $CONTAINER_NAME $1 | cut -d : -f 2 )
    RETURN_HOLDER=$RESULT
    return
}
#
# Image Lookup
#
container_image() {
    RESULT=$( $DOCKER_CMD inspect -f {{.Image}} $CONTAINER_NAME | cut -d : -f 2 )
    RETURN_HOLDER=$RESULT
    return
}
#
# Actions List
#
get_actions() {
    RESULT=""
    cd $SCRIPTS/
    for ACTION_FILE in *
    do
        [[ $RESULT = "" ]] || RESULT+=","
        RESULT+="${ACTION_FILE/$SCRIPTS\//}"
    done
    cd $CURDIR
    RETURN_HOLDER=$RESULT
    return
}
#
# Installation helper - verify replace
#
verify_install_replace() {
    TARGET=$1
    CLEAN=$2
    INSTALL=$3
    CONFIRM=$4
    if [[ -a "$TARGET" ]]; then
        if [[ $FORCE = true ]]; then
            $CLEAN
            $INSTALL
        else
            read -n 1 -p "$TARGET exists, clean it first (y/n)? "
            echo " "
            if [[ "$REPLY" == "y" ]]; then
                $CLEAN
                $INSTALL
            else
                echo "Skipping $TARGET"
            fi
        fi
    else
        $INSTALL
    fi
}
#
# Update image helper
#
update_current_image() {
	IMAGE_NAME=$1
	if [[ $UPDATE = true ]]; then
		echo "Updating image for $IMAGE_NAME"
		$DOCKER_CMD pull $IMAGE_NAME
	fi
}
#
# Download app locator
#
downloader() {
    CMD=`which curl`
    if [[ ! $CMD = "" ]]; then
        RETURN_HOLDER="curl -L -o "
        return
    fi
    CMD=`which wget`
    if [[ ! $CMD = "" ]]; then
        RETURN_HOLDER="wget -O "
        return
    fi
}
#
# Export functions to children
#
export -f signature
export -f usage
export -f verbose
export -f check
export -f not_empty
export -f container_pid
export -f container_port
export -f container_image
export -f get_actions
export -f verify_install_replace
export -f update_current_image

#
# Command references
# Alias new versions hack
#
if [ -f "/usr/bin/docker.io" ]; then
 DOCKER_CMD="docker.io"
else
 DOCKER_CMD="docker"
fi
export GIT_CMD="git"
export DOCKER_CMD

#
# Directory specifications:
# Always operates on current directory
#
HMM_DIR=$( dirname -- "$SELF_PATH" )
export HMM_TARGET_DIR=$( pwd )
export CURDIR=$HMM_TARGET_DIR
export HMM_CONFIG=${CURDIR}/config.hmm
export HMM_LOCAL_CONFIG=${HOME}/.hmm/config
export HMM_CONTROL="nsenter"
export SCRIPTS="${HMM_DIR}/.hmm"

verbose "HMM_DIR=$HMM_DIR"
verbose "SCRIPTS=$SCRIPTS"
verbose "Using $HMM_DIR/.hmm as root for HMM scripts..."

#
# Configure interactivity
#
if [ -t "$fd" ]; then
    verbose "Interactive"
	INTERACTIVE="-a stdin -a stdout -a stderr -i"
else
	verbose "Non-interative"
	INTERACTIVE=""
fi

export INTERACTIVE

#
# Test first argument for config alias
#
if [ -f "$1.hmm" ]; then
    verbose "Config alias matched, using config $1.hmm..."
    export HMM_CONFIG=${CURDIR}/${1}.hmm
    shift
fi

#
# Includes
#
if [ -f "$HMM_LOCAL_CONFIG" ]; then
	verbose "Using local config $HMM_LOCAL_CONFIG"
	source "$HMM_LOCAL_CONFIG"
fi
if [ -f "$HMM_CONFIG" ]; then
	verbose "Using config $HMM_CONFIG..."
	source "$HMM_CONFIG"
fi

#
# Parameters
#
while test $# -gt 0; do
	case "$1" in
		-U|--update)
			UPDATE=true
			shift
			;;
	    -F|--force)
	        FORCE=true
	        shift
	        ;;
	    -V|--verbose)
	        VERBOSE=true
	        shift
	        ;;
		-H|--home)
			shift
			HMM_DIR=$1
			verbose "Using home: $HMM_DIR"
			shift
			;;
		-c|--config)
			shift
			HMM_CONFIG=$1
			verbose "Using config: $HMM_CONFIG"
		    source "$HMM_CONFIG"
			verbose "Loaded config: $HMM_CONFIG"
			shift
			;;
	    --path)
	        echo "$HMM_DIR"
	        exit
	        ;;
		-p)
			shift
			if test $# -gt 0; then
				verbose "Setting $opt"
				PORTS+=" -p $1"
			else
				verbose "ERROR No port specified"
				usage
				exit 1
			fi
			shift
			;;
		--port*)
			DATA=`echo $1 | sed -e 's/^[^=]*=//g'`
			PORTS+=" -p $DATA"
			shift
			;;
	    -l)
	        shift
	        if test $# -gt 0; then
	            verbose "Linking $opt"
	            LINKING+=" --link $1"
            else
                verbose "ERROR no alias specified"
                usage
                exit 1
            fi
	        shift
	        ;;
		--link*)
			DATA=`echo $1 | sed -e 's/^[^=]*=//g'`
			LINKING+=" --link $DATA"
			shift
			;;
		-v)
			shift
			if test $# -gt 0; then
				verbose "Setting $1"
				VOLUMES+=" -v $1"
			else
				verbose "ERROR: No port specified"
				usage
				exit 1
			fi
			shift
			;;
		--vol*)
			DATA=`echo $1 | sed -e 's/^[^=]*=//g'`
			VOLUMES+=" -v $DATA"
			shift
			;;
		-e)
			shift
			if test $# -gt 0; then
				verbose "Setting $1"
				ENV_VARS+=" -e $1"
			else
				verbose "ERROR: No var specified"
				usage
				exit 1
			fi
			shift
			;;
		--env*)
			DATA=`echo $1 | sed -e 's/^[^=]*=//g'`
			ENV_VARS=" -e $DATA"
			shift
			;;
		-n|--name)
			shift
			CONTAINER_NAME=$1
			verbose "Using name: $CONTAINER_NAME"
			shift
			;;
		-R|--registry)
			shift
			REGISTRY=$1
			verbose "Using registry: $REGISTRY"
			shift
			;;
		-r|--run)
			shift
			RUN_CMD=$1
			verbose "Using command: $RUN_CMD"
			shift
			;;
		-B|--base)
			shift
			BASE=$1
			verbose "Using base: $BASE"
			shift
			;;
		-T|--tag)
			shift
			TAG=$1
			verbose "Using tag: $TAG"
			shift
			;;
		-t|--test)
			DOCKER_CMD="echo docker"
			verbose "Testing only"
			shift
			;;
		-P|--parent)
			shift
			PARENT=$1
			verbose "Using parent: $PARENT"
			shift
			;;
		-u|--user)
			shift
			CONTAINER_USER=$1
			verbose "Using username: $CONTAINER_USER"
			shift
			;;
		-C|--control)
			shift
			HMM_CONTROL=$1
			verbose "Using control: $HMM_CONTROL"
			shift
			;;
	    --upgrade)
            downloader
            DOWNLOADER=$RETURN_HOLDER
            mkdir /tmp/hmm
            echo $DOWNLOADER /tmp/hmm/hmm.tar.gz http://hmm.comfreeze.net/hmm.tar.gz
            $DOWNLOADER /tmp/hmm/hmm.tar.gz http://hmm.comfreeze.net/hmm.tar.gz
            cd /tmp/hmm
            if [[ -f hmm.tar.gz ]]; then
                tar zxvf hmm.tar.gz
                ./hmm install
            fi
            cd /tmp
            rm -rf /tmp/hmm
            cd $CUR_DIR
	        exit 0
	        ;;
		*)
			break
			;;
	esac
done

PORTS="$PORTS $ADD_PORTS"
LINKING="$LINKING $ADD_LINKING"
VOLUMES="$VOLUMES $ADD_VOLUMES"
ENV_VARS="$ENV_VARS $ADD_ENV_VARS"

#
# Simplified name without tag
#
export DOCKER_BASE="$([ "$REGISTRY" == "" ] && echo "" || echo "$REGISTRY/" )${BASE}"

#
# Fully qualified name:
# e.g. hostname.domain:port/repository:tag
#
export DOCKER_NAME="${DOCKER_BASE}$([ "$TAG" == "" ] && echo "" || echo ":$TAG" )"

#
# Friendly name:
# e.g. my-cool-server-3.0
#
if [[ $CONTAINER_NAME = "" ]]; then
    CONTAINER_NAME="$BASE"
    if [[ ! $TAG = "" ]]; then
        CONTAINER_NAME="$CONTAINER_NAME-$TAG"
    fi
fi
if [[ $CONTAINER_USER = "" ]]; then
    CONTAINER_USER="$USER"
fi
export CONTAINER_NAME

#
# Compiled launch parameters:
# e.g. -p 80:80 -v /var/www -e APP_ENV=prod
#
export CONTAINER_ARGS="$ENV_VARS $PORTS $VOLUMES $LINKING"
export CONTAINER_SSH="$SSH_PORT"
export CONTAINER_USER
export PARENT
export FORCE
export UPDATE
export RUN_CMD
export HMM_DIR
export RETURN_HOLDER
export VERBOSE
export TAG

#
# CLI User Interface
#
while test $# -gt 0; do
	case "$1" in
		-h|--help)
			signature
			usage
			exit 0
			;;
		-i|--info)
			signature
			echo "SELF_PATH:      $SELF_PATH"
			echo "HMM_DIR:        $HMM_DIR"
			echo "HMM_CONFIG:     $HMM_CONFIG"
			echo "PARENT:         $PARENT"
			echo "REGISTRY:       $REGISTRY"
			echo "BASE:           $BASE"
			echo "TAG:            $TAG"
			echo "RUN_CMD:        $RUN_CMD"
			echo "DOCKER_NAME:    $DOCKER_NAME"
			echo "CONTAINER_USER: $CONTAINER_USER"
			echo "CONTAINER_NAME: $CONTAINER_NAME"
			echo "CONTAINER_ARGS: $CONTAINER_ARGS"
			exit 0
			;;
		-a|--actions)
			signature
			cd $SCRIPTS/
			echo "Available actions:"
			for ACTION_FILE in *
			do
				echo " * ${ACTION_FILE/$SCRIPTS\//}"
			done
			cd $CURDIR
			exit 0
			;;
###MINIFY-ACTIONS###
        *)
			if [[ -f "$SCRIPTS/$1" ]]; then
				ACTION="$SCRIPTS/$1"
				verbose "ACTION: $ACTION"
				shift
			fi
            break
            ;;
	esac
done

if [ "$ACTION" != "" ]; then
	/bin/bash "$ACTION" $*
#	exit 0
else
	usage
	exit 0
fi

# echo $CONTAINER_ARGS
