#!/bin/bash

HMM_DIR="$( pwd )"
SCRIPTS="$HMM_DIR/.hmm"

BASH_COMPLETE=""
BASH_COMMANDS=""
FILENAME=""

#
# Actions List
#
get_actions() {
    TARGET=$1
    RESULT=""
    cd ${TARGET}/
    for ACTION_FILE in *
    do
    	if [[ -f ${ACTION_FILE} ]]; then
        	FILENAME="${ACTION_FILE/$SCRIPTS\//}"
            BASH_COMPLETE+=" ${FILENAME}"
            BASH_COMMANDS+="
        ${FILENAME})
            shift

# INCLUDED FILE CONTENT
$( tail -n +2 "$TARGET/$ACTION_FILE" )

            exit 0
            ;;"
        fi

        if [[ -d ${ACTION_FILE} ]]; then
            cd ${ACTION_FILE}
            for SUB_ACTION_FILE in *
            do
                FILENAME="${ACTION_FILE/$SCRIPTS\//}"
                BASH_COMPLETE+=" ${FILENAME}-$SUB_ACTION_FILE"
                BASH_COMMANDS+="
        ${FILENAME}-$SUB_ACTION_FILE)
            shift

# INCLUDED FILE CONTENT
$( tail -n +2 "$TARGET/$ACTION_FILE/$SUB_ACTION_FILE" )

            exit 0
            ;;"
			done
			cd ..
		fi
    done
    cd ${HMM_DIR}
}

#for SCRIPT in $SCRIPTS/*; do
#    FILENAME="${SCRIPT/$SCRIPTS\//}"
#    BASH_COMPLETE+=" ${FILENAME}"
#    BASH_COMMANDS+="
#        ${FILENAME})
#            shift
#
## INCLUDED FILE CONTENT
#$( tail -n +2 $SCRIPT )
#
#            exit 0
#            ;;"
#done

get_actions ${SCRIPTS}

BASH_COMPLETE+=" \\"

# echo -e "$BASH_COMPLETE"

echo "${BASH_COMPLETE}" > .compiled_options
sed -e '/^###MINIFY-ACTIONS###/r .compiled_options' hmm.bash > hmmm.bash

# echo -e "$BASH_COMMANDS"

cp hmm hmmm
echo "${BASH_COMMANDS}" > .compiled_commands
sed -e '/^###MINIFY-ACTIONS###/r .compiled_commands' hmm > hmmm
chmod a+x hmmm

rm -rf .compiled_commands
rm -rf .compiled_options
