#!/bin/bash
SOURCE_IMAGE=${BASE_OS}:express
add_port 3000
#add_volume "$( pwd ):/workspace"

update_current_image ${SOURCE_IMAGE}

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

server_command ${SOURCE_IMAGE} "node $*"
