#!/bin/bash
SOURCE_IMAGE=$BASE_OS:grunt

update_current_image $SOURCE_IMAGE

verbose "Running 'grunt serve $*' with args: $CONTAINER_ARGS"

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

$DOCKER_CMD run \
 --rm=true \
 -v "$( pwd ):/overlay" \
 -p 9000 \
 $CONTAINER_ARGS \
 $SOURCE_IMAGE "grunt serve $*"
