#!/bin/bash
SOURCE_IMAGE=$BASE_OS:nginx

update_current_image $SOURCE_IMAGE

verbose "Running NGINX with args: $CONTAINER_ARGS"

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

$DOCKER_CMD run \
 --rm=true \
 -v "$( pwd ):/webroot" \
 -p 80 \
 $CONTAINER_ARGS \
 $SOURCE_IMAGE
