#!/bin/bash
SOURCE_IMAGE=$BASE_OS:jenkins

update_current_image $SOURCE_IMAGE

verbose "Running NGINX + PHP5 with args: $CONTAINER_ARGS"

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

$DOCKER_CMD run \
 --rm=true \
 -v "$( pwd ):/var/lib/jenkins" \
 -p 8080 \
 $CONTAINER_ARGS \
 $SOURCE_IMAGE
