#!/bin/bash
SOURCE_IMAGE=${BASE_OS}:jenkins
add_port 8080
add_volume "$( pwd ):/var/lib/jenkins"

update_current_image ${SOURCE_IMAGE}

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

server_command ${SOURCE_IMAGE}
