#!/bin/bash
SOURCE_IMAGE=$BASE_OS:mongo

update_current_image $SOURCE_IMAGE

verbose "Running MongoDB with args: $CONTAINER_ARGS"

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

$DOCKER_CMD run \
 --rm=true \
 -p 27017 \
 $CONTAINER_ARGS \
 $SOURCE_IMAGE $*
