#!/bin/bash
SOURCE_IMAGE=${BASE_OS}:nginx-php5fpm
add_port 80
add_volume "$( pwd ):/webroot"

update_current_image ${SOURCE_IMAGE}

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

server_command ${SOURCE_IMAGE} $*
