#!/bin/bash
echo "Stopping $DOCKER_NAME..."

$DOCKER_CMD stop $CONTAINER_NAME

echo "Destroying $CONTAINER_NAME..."

$DOCKER_CMD rm $CONTAINER_NAME

echo "Starting $DOCKER_NAME..."

$DOCKER_CMD run \
 -i -t -d \
 --name=$CONTAINER_NAME \
 $CONTAINER_ARGS \
 $* \
 $DOCKER_NAME
