#!/bin/bash
echo "Stopping $DOCKER_NAME..."

docker stop $CONTAINER_NAME

echo "Destroying $CONTAINER_NAME..."

docker rm $CONTAINER_NAME

echo "Starting $DOCKER_NAME..."

docker run \
 -i -t -d \
 --name=$CONTAINER_NAME \
 $CONTAINER_ARGS \
 $* \
 $DOCKER_NAME
