#!/bin/bash
PORT=`$DOCKER_CMD port $CONTAINER_NAME 22 | cut -d : -f 2`

echo "Remoting into $CONTAINER_NAME - $PORT"

ssh \
 -o "LogLevel QUIET" \
 -o "StrictHostKeyChecking no" \
 -o "UserKnownHostsFile /dev/null" \
 -p $PORT \
 comfreeze@localhost
