#!/bin/bash
verbose "Running 'grunt $*' with args: $CONTAINER_ARGS"

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

$DOCKER_CMD run \
 -a stdin -a stdout -a stderr \
 -i -t --rm=true \
 -v $( pwd ):/overlay \
 $CONTAINER_ARGS \
 dockers.comfreeze.net:443/ubuntu:grunt "grunt $*"
