#!/bin/bash
echo "Initializing local directory for hmm..."

#
# Initialize configuration file
#
if [ -f "$ZED_CONFIG" ]; then
cat << EOF
REGISTRY="dockers.comfreeze.net:443"
BASE="ubuntu"
TAG=""
ENV_VARS=""
VOLUMES=""
PORTS=""
EOF > $ZED_CONFIG
fi
