#!/bin/bash
verbose "Initializing local directory for hmm..."
signature

clean_config() {
    rm -rf $HMM_CONFIG
}

real_config() {
    verbose "Generating $HMM_CONFIG"
    cat > $HMM_CONFIG <<EOF

# Parent docker registry name for spawning/reference
PARENT="${PARENT}"

# Docker registry address (if not port 80, specify port)
REGISTRY="$REGISTRY"

# Base repository in the registry
BASE="$BASE"

# Target on the repository, version in big repos, tags in small
TAG="$TAG"

# Environment variable to inject (prefix each with -e ).  Format is "-e name=value".
ENV_VARS="$ENV_VARS"

# Volumes/directories to mount/expose (prefix each with -v ).  Format is "-v (local:)internal" and only exposed if local is not provided.
VOLUMES="$VOLUMES"

# Ports to forward/manage/redirect (prefix each with -p ).  Format is "-p (local:)port" where local is dynamic if not provided.
PORTS="$PORTS"

# Links to other containers (prefix each with --link ).  Format is "-p (source:)alias" where source is container name/tag provided.
LINKING="$LINKING"

# Default username used in operations requiring one specified.
CONTAINER_USER="$CONTAINER_USER"

# Command to run for compliant systems that will support it
RUN_CMD="/bin/bash"

EOF
    verbose "Generated $HMM_CONFIG"
}

#
# Initialize configuration file
#
verify_install_replace \
 "$HMM_CONFIG" \
 clean_config \
 real_config
