#!/bin/bash
verbose "Initializing local directory for hmm..."
signature

#
# Initialize configuration file
#
if [ ! -f "$HMM_CONFIG" ]; then
    verbose "Generating $HMM_CONFIG"
    cat > $HMM_CONFIG <<EOF

# Docker registry address (if not port 80, specify port)
REGISTRY="dockers.comfreeze.net:443"

# Base repository in the registry
BASE="ubuntu"

# Target on the repository, version in big repos, tags in small
TAG=""

# Environment variable to inject (prefix each with -e ).  Format is "-e name=value".
ENV_VARS=""

# Volumes/directories to mount/expose (prefix each with -v ).  Format is "-v (local:)internal" and only exposed if local is not provided.
VOLUMES=""

# Ports to forward/manage/redirect (prefix each with -p ).  Format is "-p (local:)port" where local is dynamic if not provided.
PORTS=""
EOF
    verbose "Generated $HMM_CONFIG"
fi
