#!/bin/bash
signature

TYPE=local
HMM_INSTALL_PATH=/usr/local/lib

clean_install_local()       { sudo rm -rf "$HMM_INSTALL_PATH/hmm"; }
real_install_local()        { mkdir -p "$HMM_INSTALL_PATH"; sudo cp -R "$HMM_DIR" "$HMM_INSTALL_PATH/."; }

real_bashrc_local()         { echo "export PATH=$HMM_INSTALL_PATH/hmm:$PATH" >> $HOME/.bashrc;
                              echo ". $HMM_INSTALL_PATH/hmm.bash" >> $HOME/.bashrc; }

real_profile_local()        { echo "export PATH=$HMM_INSTALL_PATH/hmm:$PATH" >> $HOME/.bash_profile;
                              echo ". $HMM_INSTALL_PATH/hmm.bash" >> $HOME/.bash_profile; }

install_local() {
    read -e -p "Where would you like HMM installed? " -i "$HOME/bin" HMM_INSTALL_PATH
    echo " "
    echo "Installing from $HMM_DIR to $HMM_INSTALL_PATH"
    if [[ "$HMM_DIR" = "$HMM_INSTALL_PATH/hmm" ]]; then
        echo "ERROR: Same directory!"
        exit 1
    fi
    verify_install_replace \
     "$HMM_INSTALL_PATH/hmm" \
     clean_install_local \
     real_install_local

    read -n 1 -p "Append updates to $HOME/.bashrc? (y/n) "
    echo " "
    [ $REPLY = "n" ] || real_bashrc_local;

    read -n 1 -p "Append updates to $HOME/.bash_profile? (y/n) "
    echo " "
    [ $REPLY = "n" ] || real_profile_local;

    read -n 1 -p "Run bash completion setup now? (y/n) "
    echo " "
    [ $REPLY = "n" ] || /bin/bash "$HMM_INSTALL_PATH/hmm.bash";
}

clean_install_global()      { sudo rm -rf "$HMM_INSTALL_PATH/hmm"; }
real_install_global()       { sudo cp -R "$HMM_DIR" "$HMM_INSTALL_PATH/."; }

clean_completion_global()   { sudo rm -rf /etc/bash_completion.d/hmm; }
real_completion_global()    { sudo ln -s "$HMM_INSTALL_PATH/hmm/hmm.bash" /etc/bash_completion.d/hmm; }

clean_path_global()         { sudo rm -rf /usr/local/bin/hmm; }
real_path_global()          { sudo ln -s "$HMM_INSTALL_PATH/hmm/hmm" /usr/local/bin/hmm; }

install_global() {
    echo "Installing from $HMM_DIR to $HMM_INSTALL_PATH"
    sudo mkdir -p $HMM_INSTALL_PATH
    verify_install_replace \
     "$HMM_INSTALL_PATH/hmm" \
     clean_install_global \
     real_install_global

    sudo mkdir -p $HMM_INSTALL_PATH
    verify_install_replace \
     "/etc/bash_completion.d/hmm" \
     clean_completion_global \
     real_completion_global
    /bin/bash /etc/bash_completion.d/hmm

    sudo mkdir -p $HMM_INSTALL_PATH
    verify_install_replace \
     "/usr/local/bin/hmm" \
     clean_path_global \
     real_path_global
}

read -n 1 -p "What type of installation? (l)ocal, (g)lobal "
echo " "
[ $REPLY = "l" ] && install_local;
[ $REPLY = "g" ] && install_global;
