#!/bin/bash
verbose "Installing HMM"

pathadd() {
    if [ -d "$1" ] && [[ ":$PATH:" != *":$1:"* ]]; then
        export PATH="${PATH:+"$PATH:"}$1"
    fi
}

if [ ! -d "~/bin" ]; then
 mkdir -p ~/bin
 pathadd ~/bin
 echo 'PATH=~/bin:$PATH' >> ~/.bash_profile
 source ~/.bash_profile
fi

cd ~/bin

if [ ! -f "zed" ]; then
 verbose "Creating link in ~/bin"
 /bin/ln -s $HMM zed
else
 verbose "Existing link intact"
fi

