#!/bin/bash

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"
#not_empty "$DOCKER_NAME" "DOCKER_NAME not found!"

verbose "Purging local docker storage..."

$DOCKER_CMD ps -a --no-trunc=true | grep 'Exit' | awk '{print $1}' | xargs -L 1 -r $DOCKER_CMD rm

$DOCKER_CMD images -a --no-trunc=true | awk '{print $3}' | xargs $DOCKER_CMD rmi -f
