#!/bin/bash

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"
not_empty "$DOCKER_NAME" "DOCKER_NAME not found!"
not_empty "$CONTAINER_NAME" "CONTAINER_NAME empty!"

verbose "Stopping $DOCKER_NAME..."
$DOCKER_CMD stop $CONTAINER_NAME

verbose "Destroying $CONTAINER_NAME..."
$DOCKER_CMD rm $CONTAINER_NAME

verbose "Starting $DOCKER_NAME..."
$DOCKER_CMD run \
 -i -t -d \
 --name=$CONTAINER_NAME \
 $CONTAINER_ARGS \
 $* \
 $DOCKER_NAME