#!/bin/bash
echo "Running '$*' in $DOCKER_NAME with args:"
echo $CONTAINER_ARGS
echo " "

$DOCKER_CMD run \
 -a stdin \
 -a stdout \
 -a stderr \
 -i -t --rm=true \
 --name=$CONTAINER_NAME \
 $CONTAINER_ARGS \
 $DOCKER_NAME \
 "$*" 
