#!/bin/bash
verbose "Running NGINX with args: $CONTAINER_ARGS"

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

$DOCKER_CMD run \
 --rm=true \
 -v $( pwd ):/webroot \
 -p 80 \
 dockers.comfreeze.net:443/ubuntu:nginx
