#!/bin/bash
verbose "Running 'node $*' with args: $CONTAINER_ARGS"

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

$DOCKER_CMD run \
 --rm=true \
 -v "$( pwd ):/workspace" \
 -p 3000 \
 dockers.comfreeze.net:443/ubuntu:express "node $*"
