#!/bin/bash
SOURCE_IMAGE=dockers.comfreeze.net:443/ubuntu:redis

update_current_image $SOURCE_IMAGE

verbose "Starting Redis server with args: $CONTAINER_ARGS"

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

$DOCKER_CMD run \
 --rm=true \
 -v "$( pwd ):/overlay" \
 $CONTAINER_ARGS \
 $SOURCE_IMAGE
