#!/bin/bash
verbose "Running 'grunt serve $*' with args: $CONTAINER_ARGS"

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"

$DOCKER_CMD run \
 --rm=true \
 -v $( pwd ):/overlay \
 -p 9000 \
 dockers.comfreeze.net:443/ubuntu:grunt "grunt serve $*"
