#!/bin/bash
verbose "Running '$*' in $DOCKER_NAME with args: $CONTAINER_ARGS"

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"
not_empty "$PARENT" "PARENT is not defined!"

update_current_image $PARENT

$DOCKER_CMD run  \
$INTERACTIVE -t --rm=true \
 $CONTAINER_ARGS \
 $PARENT \
 "$RUN_CMD $*"