#!/bin/bash

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"
not_empty "$DOCKER_NAME" "DOCKER_NAME not found!"
not_empty "$CONTAINER_NAME" "CONTAINER_NAME empty!"

verbose "Launching $DOCKER_NAME with args: $CONTAINER_ARGS"
$DOCKER_CMD run \
$INTERACTIVE -t -d \
 --name=$CONTAINER_NAME \
 $CONTAINER_ARGS \
 $* \
 $DOCKER_NAME \
 "$RUN_CMD"
