#!/bin/bash
verbose "Running '$*' in $DOCKER_NAME with args: $CONTAINER_ARGS"

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"
not_empty "$CONTAINER_NAME" "CONTAINER_NAME empty!"
not_empty "$PARENT" "PARENT is not defined!"

echo "TESTING"

$DOCKER_CMD run \
 -a stdin -a stdout -a stderr \
 -i -t --rm=true \
 --name=$CONTAINER_NAME \
 $CONTAINER_ARGS \
 $PARENT "$*"
