#!/bin/bash
container_port 22
PORT=$RETURN_HOLDER

verbose "Remoting into $CONTAINER_NAME - $PORT"

ssh -t -o "LogLevel QUIET" -o "StrictHostKeyChecking no" -o "UserKnownHostsFile /dev/null" -p $PORT comfreeze@localhost $*
