#!/bin/bash

not_empty "$DOCKER_CMD" "DOCKER_CMD not found!"
not_empty "$DOCKER_BASE" "$DOCKER_BASE not found!"
not_empty "$CONTAINER_NAME" "CONTAINER_NAME empty!"

container_image
IMAGE=$RETURN_HOLDER

verbose "Tagging $CONTAINER_NAME..."
$DOCKER_CMD tag $IMAGE $DOCKER_BASE-${1-$TAG}
